# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 2.6
    - 2.7
## Disabled for a while:
#    - 3.2
#    - 3.3
#matrix:
#    include:
#        - python: 2.4
#          env: FULL="true"
#        - python: 2.5
#          env: FULL="true"
#        - python: 2.6
#          env: FULL="true"
#        - python: 2.7
#          env: FULL="true"
##        - python: 3.2
##          env: LANG="en_US.utf-8"
install:
    - if [[ $TRAVIS_PYTHON_VERSION < '2.6' ]]; then pip install --use-mirrors simplejson PyYAML pep8; else pip install --use-mirrors PyYAML pep8; fi
    - pip install --use-mirrors anyconfig
    # see: https://github.com/guillermo-carrasco/bcbio-nextgen-deploy/commit/dabb3903ffdb29743b15c76eb535e7ae14885cad
    # see: https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
    - "./aux/runtest.sh"
